"""Build the About Us page using the storefront's shared header and footer."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
index = (ROOT / 'index.html').read_text()
header = index[index.index('<div class="announcement">'):index.index('</header>') + len('</header>')]
footer = index[index.index('<footer class="footer">'):index.index('</footer>') + len('</footer>')]
contact = (ROOT / 'partials/contact.html').read_text()
for anchor in ('top', 'brands', 'contact', 'contact-us', 'categories', 'products'):
    header = header.replace(f'href="#{anchor}"', f'href="index.html#{anchor}"')
    footer = footer.replace(f'href="#{anchor}"', f'href="index.html#{anchor}"')
header = header.replace('href="index.html#contact-us"', 'href="#contact-us"')

page = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#0b0b0d"><meta name="description" content="Get to know Sherpa Quest Nepal, a Nepal-based destination for motorcycle riding gear, helmets, luggage and off-road accessories.">
<title>About Us | Sherpa Quest Nepal</title><link rel="icon" type="image/svg+xml" href="assets/favicon.svg">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700;800;900&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="styles.css?v=3"><link rel="stylesheet" href="about.css?v=3"><link rel="stylesheet" href="theme.css?v=4"><script defer src="navigation.js?v=5"></script><script defer src="floating-promo.js"></script><script defer src="contact-form.js"></script></head>
<body><a class="skip" href="#main">Skip to content</a>{header}
<main id="main">
  <section class="about-hero"><img src="assets/sherpa-hero.png" alt="Motorcyclist riding through a mountain landscape in Nepal"><div class="about-hero-shade"></div><div class="shell about-hero-copy"><p class="eyebrow light">SHERPA QUEST NEPAL</p><h1>NEPAL'S BIGGEST<br><em>RETAIL &amp; WHOLESALE</em><br>DESTINATION.</h1><p>Motorcycle gear, luggage and accessories for individual riders and businesses.</p></div></section>
  <section class="about-story shell"><div><p class="eyebrow">ABOUT SHERPA QUEST</p><h2>BUILT AROUND<br><em>THE RIDE.</em></h2></div><div class="about-story-copy"><p>Sherpa Quest Nepal brings motorcycle accessories and riding gear together for individual riders, retailers and wholesale buyers. Our selection spans helmets, jackets, gloves, boots, rider tech, protection, touring luggage and the smaller essentials that make a journey easier.</p><p>From a daily commute to a long route through the mountains, we help people find equipment that fits their bike, their plans and their budget. Retail customers can ask about sizing and available colors; business buyers can discuss quantities and supply directly with our team.</p></div></section>
  <section class="about-offer"><div class="shell"><div class="about-offer-head"><p class="eyebrow">WHAT WE DO</p><h2>GEAR FOR RIDERS.<br><em>SUPPLY FOR BUSINESSES.</em></h2></div><div class="about-offer-grid"><article><span>01 / RETAIL</span><h3>Find your next essential</h3><p>Explore gear for safety, comfort and carrying what matters. Ask us about fit, colors and current availability before you choose.</p></article><article><span>02 / WHOLESALE</span><h3>Source for your store</h3><p>Tell us the product lines and quantities you need. We will discuss available stock and wholesale options for your business.</p></article><article><span>03 / RIDER SUPPORT</span><h3>Choose with confidence</h3><p>Browse product photos and details, then speak with us about the gear that suits your motorcycle and route.</p></article></div></div></section>
  <section class="about-experience shell"><div class="section-head"><div><p class="eyebrow">THE CUSTOMER RIDER EXPERIENCE</p><h2>EXPLORE. ASK.<br><em>RIDE READY.</em></h2></div><p>Take time to compare gear and talk through your next adventure.</p></div><div class="experience-grid"><a class="experience-card" href="#contact-us"><span class="experience-photo"><img src="assets/rider-experience-lounge.jpeg" alt="Seating area with motorcycle posters and a sofa" loading="lazy"></span><span class="experience-copy"><small>01 / VISIT</small><strong>A SPACE FOR RIDERS</strong><span>See the gear, take a seat and tell us what you need.</span></span></a><a class="experience-card" href="index.html?category=Helmets#products"><span class="experience-photo"><img src="assets/products/ilm-129-helmet/gloss-white-01.jpg" alt="ILM motorcycle helmet" loading="lazy"></span><span class="experience-copy"><small>02 / EXPLORE</small><strong>COMPARE YOUR OPTIONS</strong><span>Browse colors, details and fit before deciding.</span></span></a><a class="experience-card" href="riders.html"><span class="experience-photo"><img src="assets/banners/high-pass-road.webp" alt="Mountain road in Nepal" loading="lazy"></span><span class="experience-copy"><small>03 / GO FURTHER</small><strong>READY FOR THE ROAD</strong><span>Find equipment for the routes you want to take.</span></span></a></div></section>
  <section class="about-why"><div class="shell"><div class="section-head"><div><p class="eyebrow">WHY SHERPA QUEST</p><h2>WHY RIDERS<br><em>CHOOSE US.</em></h2></div></div><div class="why-grid">
    <article class="why-feature"><img src="assets/banners/high-pass-road.webp" alt="Winding mountain road in Nepal" loading="lazy"><span class="why-kicker">BUILT AROUND THE RIDE</span><div><h3>Gear for every road ahead</h3><p>From city commutes to mountain routes, explore protection, luggage and useful motorcycle accessories in one place.</p></div></article>
    <article class="why-card"><span class="why-card-icon" aria-hidden="true">01</span><h3>Retail &amp; wholesale</h3><p>Shop for your own ride or enquire about stock for your business.</p></article>
    <article class="why-card"><span class="why-card-icon" aria-hidden="true">02</span><h3>Riding protection</h3><p>Explore helmets, jackets, gloves, boots and guards from our catalog.</p></article>
    <article class="why-card"><span class="why-card-icon" aria-hidden="true">03</span><h3>Touring luggage</h3><p>Find backpacks, dry bags, panniers and other ways to carry your kit.</p></article>
    <article class="why-card"><span class="why-card-icon" aria-hidden="true">04</span><h3>Rider tech</h3><p>Browse intercoms and phone mounts alongside riding essentials.</p></article>
    <article class="why-card"><span class="why-card-icon" aria-hidden="true">05</span><h3>Color &amp; fit choices</h3><p>See available product options and ask us about the fit you need.</p></article>
    <article class="why-card"><span class="why-card-icon" aria-hidden="true">06</span><h3>Product details</h3><p>Compare photos, features and specifications before you enquire.</p></article>
    <article class="why-card"><span class="why-card-icon" aria-hidden="true">07</span><h3>Kathmandu contact</h3><p>Reach our team by phone, email or WhatsApp for current availability.</p></article>
    <article class="why-card"><span class="why-card-icon" aria-hidden="true">08</span><h3>Built for Nepal</h3><p>Choose gear with Nepal's changing roads and riding plans in mind.</p></article>
  </div></div></section>
  <section class="about-categories"><div class="shell"><p class="eyebrow">OUR PRODUCT RANGE</p><h2>READY FOR YOUR<br><em>NEXT ROUTE.</em></h2><div class="about-category-grid"><a href="index.html?category=Helmets#products">HELMETS</a><a href="index.html?category=Riding%20jackets#products">RIDING JACKETS</a><a href="index.html?category=Gloves#products">GLOVES</a><a href="index.html?category=Boots#products">BOOTS</a><a href="index.html?category=Luggage%20%26%20bags#products">LUGGAGE &amp; BACKPACKS</a><a href="index.html?category=Intercom#products">RIDER TECH</a></div></div></section>
  <section class="about-connection shell"><div><p class="eyebrow">RIDE OR RETAIL</p><h2>LET'S GET<br><em>YOU READY.</em></h2><p>Use the enquiry form below to tell us whether you are shopping for yourself or sourcing gear for a business.</p><a class="about-enquiry-link" href="#contact-us">SEND AN ENQUIRY</a></div><div class="about-contact-links"><a href="tel:+9779744464587"><small>CALL US</small><strong>+977 974-4464587</strong></a><a href="mailto:sherpaquestoffroad@gmail.com"><small>EMAIL US</small><strong>sherpaquestoffroad@gmail.com</strong></a><a href="https://wa.me/9779744464587" target="_blank" rel="noopener"><small>MESSAGE US</small><strong>WhatsApp Sherpa Quest Nepal</strong></a></div></section>
</main>{contact}{footer}
<a class="floating-chat" href="https://wa.me/9779744464587" target="_blank" rel="noopener" aria-label="Chat with Sherpa Quest Nepal on WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.6a8.5 8.5 0 0 1-12.4 7.5L3 20.5l1.4-5A8.5 8.5 0 1 1 20.5 11.6Z"/><path d="M8.7 8.2c-.4 0-.9.7-.8 1.4.1 1.4 2 4 4.3 5.2 1.5.8 2.7.7 3.3.1l.6-.8-2.1-1-1 .9a7.6 7.6 0 0 1-3-3.1l.8-.9-.9-1.9Z"/></svg><span>CHAT WITH US</span></a>
</body></html>'''
(ROOT / 'about.html').write_text(page)
print('Built about.html')
